<?php
// $Id$

function first_help($path, $arg){
	if($path == 'admin/help#first'){
		return t('A demonstration module');
	}
	
}

/**
* Implements hook_block_info().
*/
function first_block_info() {
	$blocks = array();
	$blocks['list_modules'] = array(
	'info' => t('A listing of all of the enabled modules.'),
	'cache' => DRUPAL_NO_CACHE,
	);
	return $blocks;
}
/**
* Implements hook_block_view().
*/
function first_block_view($block_name = '') {
	if ($block_name == 'list_modules') {
		$list = module_list();
		$theme_args = array('items' => $list, 'type' => 'ol');
		$content = theme('item_list', $theme_args);
		$block = array(
		'subject' => t('Enabled Modules'),
		'content' => $content,
		);
		return $block;
	}
}

function first_perm(){
	
}

function first_menu(){
	$items['first/add'] = array(
    'title' => 'My Request Form',
    'description' => 'The form is for learning Form API.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('first_my_form'),
    'access callback' => TRUE,
    'menu_name' =>'management',
    //'access arguments' => array('administer artworks'),
    //'file' => 'artwork.admin.inc',
  );
  
  return $items;
  
}


function first_my_form(){
  $form = array();
  $form['my_button'] = array(
  '#type'=> 'submit',
  '#value'=>t('Perform Action'),
  );
  return $form;
  
}

